# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:/Users/Christian/AppData/Local/Temp/telaqhCoJD.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1112, 887)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.frame_modulo_vendas = QtWidgets.QFrame(self.centralwidget)
        self.frame_modulo_vendas.setGeometry(QtCore.QRect(10, 10, 1101, 741))
        self.frame_modulo_vendas.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_modulo_vendas.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_modulo_vendas.setObjectName("frame_modulo_vendas")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.frame_modulo_vendas)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.lst_itens = QtWidgets.QPlainTextEdit(self.frame_modulo_vendas)
        self.lst_itens.setObjectName("lst_itens")
        self.gridLayout.addWidget(self.lst_itens, 0, 2, 2, 1)
        self.lbl_total = QtWidgets.QLabel(self.frame_modulo_vendas)
        font = QtGui.QFont()
        font.setPointSize(30)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.lbl_total.setFont(font)
        self.lbl_total.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lbl_total.setObjectName("lbl_total")
        self.gridLayout.addWidget(self.lbl_total, 2, 2, 1, 1)
        self.txt_ean = QtWidgets.QTextEdit(self.frame_modulo_vendas)
        self.txt_ean.setMaximumSize(QtCore.QSize(600, 50))
        self.txt_ean.setObjectName("txt_ean")
        self.gridLayout.addWidget(self.txt_ean, 2, 0, 1, 1)
        self.lbl_item = QtWidgets.QLabel(self.frame_modulo_vendas)
        self.lbl_item.setMaximumSize(QtCore.QSize(540, 50))
        font = QtGui.QFont()
        font.setPointSize(30)
        font.setItalic(True)
        self.lbl_item.setFont(font)
        self.lbl_item.setObjectName("lbl_item")
        self.gridLayout.addWidget(self.lbl_item, 1, 0, 1, 1)
        self.label = QtWidgets.QLabel(self.frame_modulo_vendas)
        self.label.setText("")
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 0, 1, 1)
        self.lbl_rodape = QtWidgets.QLabel(self.frame_modulo_vendas)
        self.lbl_rodape.setMaximumSize(QtCore.QSize(16777215, 30))
        self.lbl_rodape.setObjectName("lbl_rodape")
        self.gridLayout.addWidget(self.lbl_rodape, 3, 0, 1, 3)
        self.gridLayout_2.addLayout(self.gridLayout, 0, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "SisVendas 2023"))
        self.lbl_total.setText(_translate("MainWindow", "TextLabel"))
        self.lbl_item.setText(_translate("MainWindow", "Item"))
        self.lbl_rodape.setText(_translate("MainWindow", "TextLabel"))
